# Generated by Django 3.2.6 on 2021-12-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0002_auto_20211208_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('no_ktp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('P', 'Perempuan'), ('L', 'Laki-laki')], max_length=10)),
                ('address', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(choices=[('Tamu', 'Pengunjung'), ('Penghuni', 'penghuni')], max_length=10)),
                ('img', models.ImageField(upload_to='images/')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.AlterField(
            model_name='log',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verif.vehicle'),
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verif.person'),
        ),
        migrations.AddField(
            model_name='owner',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verif.vehicle'),
        ),
    ]
