# Generated by Django 3.2.6 on 2021-12-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0004_auto_20211221_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='face',
            name='ticketno',
            field=models.IntegerField(default=0),
        ),
    ]
