# Generated by Django 3.2.6 on 2021-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0005_auto_20211221_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
