# Generated by Django 3.2.6 on 2021-12-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0007_alter_person_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
