# Generated by Django 3.2.6 on 2022-01-05 11:19

from django.db import migrations, models
import verif.models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0008_face_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=verif.models.person_directory_path),
        ),
    ]
