# Generated by Django 3.2.6 on 2022-01-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0009_alter_person_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicleType',
            new_name='vehicle_Type',
        ),
    ]
