# Generated by Django 3.2.6 on 2022-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0010_rename_vehicletype_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpCam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
