# Generated by Django 3.2.6 on 2022-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0012_rename_ip_ipcam_rtsp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='name',
        ),
        migrations.AddField(
            model_name='face',
            name='recorded_by',
            field=models.ManyToManyField(to='verif.IpCam'),
        ),
    ]
