# Generated by Django 3.2.6 on 2022-01-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0015_auto_20220129_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
