# Generated by Django 3.2.6 on 2022-01-31 10:13

from django.db import migrations, models
import verif.models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0016_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastface',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=verif.models.face_directory_path),
        ),
    ]
