# Generated by Django 3.2.6 on 2022-02-02 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0019_auto_20220131_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpCam',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.OneToOneField(default='Unregisted', on_delete=django.db.models.deletion.CASCADE, to='verif.person'),
        ),
    ]
