# Generated by Django 3.2.6 on 2022-02-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif', '0020_auto_20220202_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastface',
            name='cosine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lastface',
            name='euclidean',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
